project_id = "rtnefktbfthopgfoswwm"

[functions.autocomplete-prompt]
verify_jwt = false

[functions.optimize-prompt]
verify_jwt = false

[functions.extract-prompt]
verify_jwt = false

[functions.translate-comment]
verify_jwt = false

[functions.enhance-image]
verify_jwt = false

[functions.personalize-prompt]
verify_jwt = false

[functions.generate-personalized-image]
verify_jwt = false
