project_id = "yppxuihzajbdtpuejyvs"

[functions.autocomplete-prompt]
verify_jwt = false

[functions.optimize-prompt]
verify_jwt = false

[functions.extract-prompt]
verify_jwt = false

[functions.translate-comment]
verify_jwt = false
