// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yppxuihzajbdtpuejyvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwcHh1aWh6YWpiZHRwdWVqeXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzUwMDUsImV4cCI6MjA3NTcxMTAwNX0.yDWmf4QDXmj1zys7T5Iz3Klmm9p46aMiHMM2vQJKDxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});